{
 "title": "Red Hat AMQ Broker",
 "description": "Dashboard for monitoring Red Hat AMQ Broker",
 "tags": [
  "amq",
  "red hat"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jvm_info{service=\"broker-amq-prometheus\"}, namespace)"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(jvm_info{service=\"broker-amq-prometheus\", namespace=\"$namespace\"}, service)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_info{service=\"broker-amq-prometheus\", namespace=\"$namespace\", service=\"$broker\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_info{kubernetes_namespace=\"$namespace\",service=\"$broker\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_uptime_millis{instance=\"$instance\"} / 1000 / 60"
    }
   ]
  },
  {
   "title": "Started",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "artemis_started{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Free File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\"} - process_open_fds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Journal Buffer Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_journal_buffer_size{instance=\"$instance\"}"
    },
    {}
   ]
  },
  {
   "title": "Address Paging",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "artemis_paging{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Journal Buffer Timeout",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_journal_buffer_timeout{instance=\"$instance\"}"
    },
    {}
   ]
  },
  {
   "title": "Journal Max I/O",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "artemis_journal_max_io{instance=\"$instance\"}"
    },
    {}
   ]
  },
  {
   "title": "Message Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_message_count{instance=\"$instance\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Connections and Consumers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "artemis_connection_count{instance=\"$instance\"}",
     "legendFormat": "Connection Count"
    },
    {
     "expr": "artemis_consumer_count{instance=\"$instance\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "Artemis Address Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "artemis_address_size{instance=\"$instance\"}",
     "legendFormat": "{{ address }}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"$instance\"}",
     "legendFormat": "{{ area }} "
    }
   ]
  },
  {
   "title": "JVM Memory Pool Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\"}",
     "legendFormat": "{{ pool }} "
    }
   ]
  },
  {
   "title": "JVM GC Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{instance=\"$instance\"}",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "jvm_threads_peak{instance=\"$instance\"}",
     "legendFormat": "Peak"
    }
   ]
  }
 ]
}